package org.quuux.crier;

import java.util.Map;
import java.util.HashMap;

public class GeoLocator {
    String[][] area_codes = {
	{ "201", "Northern New Jersey" },
	{ "202", "Washington D.C." },
	{ "203", "Connecticut" },
	{ "204", "Canada" },
	{ "205", "Central Alabama" },
	{ "206", "Western Washington State" },
	{ "207", "Maine" },
	{ "208", "Idaho" },
	{ "209", "Centeral California" },
	{ "210", "Southern Texas" },
	{ "211", "Unknown" },
	{ "212", "New York City" },
	{ "213", "Southern California" },
	{ "214", "Texas" },
	{ "215", "South Eastern Pennsylvania" },
	{ "216", "Cleveland" },
	{ "217", "Centeral Illinois" },
	{ "218", "Northern Minnesota" },
	{ "219", "North Western Indiana" },
	{ "224", "Northern Illinois" },
	{ "225", "Louisiana" },
	{ "226", "Canada" },
	{ "228", "Southern Mississippi" },
	{ "229", "South Western Georgia" },
	{ "231", "Western Michigan" },
	{ "234", "North Eastern Ohio" },
	{ "236", "Virginia" },
	{ "239", "Florida" },
	{ "240", "Western Maryland" },
	{ "242", "Bahamas" },
	{ "246", "Barbados" },
	{ "248", "Michigan" },
	{ "250", "Canada" },
	{ "251", "Southern Alabama" },
	{ "252", "Eastern North Carolina" },
	{ "253", "Washington" },
	{ "254", "Central Texas" },
	{ "256", "Eastern or Northern Alabama" },
	{ "260", "North Eastern Indiana" },
	{ "262", "South Eastern Wisconsin" },
	{ "264", "Anguilla" },
	{ "267", "South Eastern Pennsylvania" },
	{ "268", "Antigua or Barbuda" },
	{ "269", "South Western Michigan" },
	{ "270", "Western Kentucky" },
	{ "276", "Southern or South Western Virginia" },
	{ "278", "Michigan" },
	{ "281", "Texas" },
	{ "283", "South Western Ohio" },
	{ "284", "British Virgin Islands" },
	{ "289", "Canada" },
	{ "301", "Western Maryland" },
	{ "302", "Delaware" },
	{ "303", "Central Colorado" },
	{ "304", "West Virginia" },
	{ "305", "South Eastern Florida" },
	{ "306", "Canada" },
	{ "307", "Wyoming" },
	{ "308", "Western Nebraska" },
	{ "309", "Western Central Illinois" },
	{ "310", "Southern California" },
	{ "311", "Unknown" },
	{ "312", "Illinois" },
	{ "313", "Michigan" },
	{ "314", "South Eastern Missouri" },
	{ "315", "Northern Central New York" },
	{ "316", "Southern Kansas" },
	{ "317", "Central Indiana" },
	{ "318", "Northern Louisiana" },
	{ "319", "Eastern Iowa" },
	{ "320", "Central Minnesota" },
	{ "321", "Florida" },
	{ "323", "Southern California" },
	{ "325", "Central Texas" },
	{ "330", "North Eastern Ohio" },
	{ "331", "North Eastern Illinois" },
	{ "334", "Southern Alabama" },
	{ "336", "Central North Carolina" },
	{ "337", "South Western Louisiana" },
	{ "339", "Massachusetts" },
	{ "340", "United States Virgin Islands" },
	{ "341", "Unknown" },
	{ "345", "Cayman Islands" },
	{ "347", "New York" },
	{ "351", "Massachusetts" },
	{ "352", "Florida" },
	{ "360", "Western Washington State" },
	{ "361", "Southern Texas" },
	{ "369", "Solano County" },
	{ "380", "Ohio" },
	{ "385", "Utah" },
	{ "386", "Northern central Florida" },
	{ "401", "Rhode Island" },
	{ "402", "Eastern Nebraska" },
	{ "403", "Canada" },
	{ "404", "Northern Georgia" },
	{ "405", "Western Oklahoma" },
	{ "406", "Montana" },
	{ "407", "Central Florida" },
	{ "408", "Central Coastal California" },
	{ "409", "South Eastern Texas" },
	{ "410", "Eastern Maryland" },
	{ "411", "Unknown" },
	{ "412", "Western Pennsylvania" },
	{ "413", "Western Massachusetts" },
	{ "414", "South Eastern Wisconsin" },
	{ "415", "California" },
	{ "416", "Canada" },
	{ "417", "South Western Missouri" },
	{ "418", "Canada" },
	{ "419", "North Western Ohio" },
	{ "423", "Eastern Tennessee" },
	{ "424", "Southern California" },
	{ "425", "Washington" },
	{ "430", "North Eastern Texas" },
	{ "432", "Western Texas" },
	{ "434", "Eastern Virginia" },
	{ "435", "Utah" },
	{ "438", "Canada" },
	{ "440", "Ohio" },
	{ "441", "Bermuda" },
	{ "442", "Far north suburbs of San Diego" },
	{ "443", "Eastern Maryland" },
	{ "450", "Canada" },
	{ "456", "International" },
	{ "464", "Illinois" },
	{ "469", "Texas" },
	{ "470", "Georgia" },
	{ "473", "Grenada" },
	{ "475", "Connecticut" },
	{ "478", "Central Georgia" },
	{ "479", "North Western Arkansas" },
	{ "480", "Arizona" },
	{ "484", "South Eastern Pennsylvania" },
	{ "500", "Personal Communication Service" },
	{ "501", "Central Arkansas" },
	{ "502", "Northern Central Kentucky" },
	{ "503", "Oregon" },
	{ "504", "Eastern Louisiana" },
	{ "505", "North Central or North Western New Mexico" },
	{ "506", "Canada" },
	{ "507", "Southern Minnesota" },
	{ "508", "Central Massachusetts" },
	{ "509", "Eastern or Central Washington state" },
	{ "510", "California" },
	{ "511", "Nationwide travel information" },
	{ "512", "Southern Texas" },
	{ "513", "South Western Ohio" },
	{ "514", "Canada" },
	{ "515", "Central Iowa" },
	{ "516", "New York" },
	{ "517", "Central Michigan" },
	{ "518", "North Eastern New York" },
	{ "519", "Canada" },
	{ "520", "South Eastern Arizona" },
	{ "530", "North Eastern California" },
	{ "540", "Western or Southwest Virginia" },
	{ "541", "Oregon" },
	{ "551", "Northern New Jersey" },
	{ "555", "Directory Assistance" },
	{ "557", "South Eastern Missouri" },
	{ "559", "Central California" },
	{ "561", "Southern Central Florida" },
	{ "562", "California" },
	{ "563", "Eastern Iowa" },
	{ "564", "Western Washington State" },
	{ "567", "North Western Ohio" },
	{ "570", "North Eastern or Northern Central Pennsylvania" },
	{ "571", "Northern Virginia" },
	{ "573", "South Eastern Missouri" },
	{ "574", "Northern Indiana" },
	{ "575", "New Mexico" },
	{ "580", "Western Oklahoma" },
	{ "585", "North Western New York" },
	{ "586", "Michigan" },
	{ "600", "Canadian Services" },
	{ "601", "Mississippi" },
	{ "602", "Arizona" },
	{ "603", "New Hampshire" },
	{ "604", "Canada" },
	{ "605", "South Dakota" },
	{ "606", "Eastern Kentucky" },
	{ "607", "Southern Central New York" },
	{ "608", "South Western Wisconsin" },
	{ "609", "Southern New Jersey" },
	{ "610", "South Eastern Pennsylvania" },
	{ "611", "Reserved" },
	{ "612", "Central Minnesota" },
	{ "613", "Canada" },
	{ "614", "South Eastern Ohio" },
	{ "615", "Northern Middle Tennessee" },
	{ "616", "Western Michigan" },
	{ "617", "Massachusetts" },
	{ "618", "Southern Illinois" },
	{ "619", "Southern California" },
	{ "620", "Southern Kansas" },
	{ "623", "Arizona" },
	{ "626", "Eastern Southern California" },
	{ "627", "Northern California" },
	{ "628", "Unknown" },
	{ "630", "North Eastern Illinois" },
	{ "631", "New York" },
	{ "636", "Missouri" },
	{ "641", "Iowa" },
	{ "646", "New York" },
	{ "647", "Canada" },
	{ "649", "Turks or Caicos Islands" },
	{ "650", "California" },
	{ "651", "Central Minnesota" },
	{ "660", "Northern Missouri" },
	{ "661", "California" },
	{ "662", "Northern Mississippi" },
	{ "664", "Montserrat" },
	{ "669", "Central Coastal California" },
	{ "670", "Northern Mariana Islands" },
	{ "671", "Guam" },
	{ "678", "Northern Georgia" },
	{ "679", "Michigan" },
	{ "682", "Texas" },
	{ "684", "American Samoa" },
	{ "689", "Central Florida" },
	{ "700", "Unknown" },
	{ "701", "North Dakota" },
	{ "702", "Southern Nevada" },
	{ "703", "Northern Virginia" },
	{ "704", "Western North Carolina" },
	{ "705", "Canada" },
	{ "706", "Northern Georgia" },
	{ "707", "North Western California" },
	{ "708", "Illinois" },
	{ "709", "Canada" },
	{ "710", "United States Government" },
	{ "711", "Telecommunications Relay Services" },
	{ "712", "Western Iowa" },
	{ "713", "Mid South Eastern Texas" },
	{ "714", "North or Central Orange County" },
	{ "715", "Northern Wisconsin" },
	{ "716", "North Western New York" },
	{ "717", "Eastern Pennsylvania" },
	{ "718", "New York City" },
	{ "719", "South Eastern Colorado" },
	{ "720", "Central Colorado" },
	{ "724", "South Western Pennsylvania" },
	{ "727", "Florida Tampa Metro" },
	{ "731", "Western Tennessee" },
	{ "732", "Central New Jersey" },
	{ "734", "South Eastern Michigan" },
	{ "737", "Southern Texas" },
	{ "740", "South Eastern Ohio" },
	{ "747", "Southern California" },
	{ "754", "Florida" },
	{ "757", "Eastern Virginia" },
	{ "758", "St. Lucia" },
	{ "760", "California" },
	{ "762", "Northern Georgia" },
	{ "763", "Minnesota" },
	{ "764", "Unknown" },
	{ "765", "Indiana" },
	{ "767", "Dominica" },
	{ "769", "Mississippi" },
	{ "770", "Georgia" },
	{ "772", "Southern Central Florida" },
	{ "773", "Illinois" },
	{ "774", "Central Massachusetts" },
	{ "775", "Northern Nevada" },
	{ "778", "Canada" },
	{ "779", "North Western Illinois" },
	{ "780", "Canada" },
	{ "781", "Massachusetts" },
	{ "784", "Saint Vincent or Grenadines" },
	{ "785", "Northern or Western Kansas" },
	{ "786", "South Eastern Florida" },
	{ "787", "Puerto Rico" },
	{ "800", "Toll Free" },
	{ "801", "Utah" },
	{ "802", "Vermont" },
	{ "803", "South Carolina" },
	{ "804", "Eastern Virginia" },
	{ "805", "Southern Central or Central Coastal California" },
	{ "806", "Texas" },
	{ "807", "Canada" },
	{ "808", "Hawaii" },
	{ "809", "Dominican Republic" },
	{ "810", "Eastern Michigan" },
	{ "811", "Unknown" },
	{ "812", "Southern Indiana" },
	{ "813", "South Western Florida" },
	{ "814", "Central Pennsylvania" },
	{ "815", "North Western Illinois" },
	{ "816", "Northern Missouri" },
	{ "817", "Northern Central Texas" },
	{ "818", "Southern California" },
	{ "819", "North Western Quebec" },
	{ "822", "Toll Free" },
	{ "828", "Western North Carolina" },
	{ "829", "Dominican Republic" },
	{ "830", "Texas" },
	{ "831", "California" },
	{ "832", "Texas" },
	{ "833", "Toll Free" },
	{ "835", "South Eastern Pennsylvania" },
	{ "843", "South Carolina" },
	{ "844", "Toll Free" },
	{ "845", "New York" },
	{ "847", "Northern North Eastern Illinois" },
	{ "848", "Central New Jersey" },
	{ "850", "Florida" },
	{ "855", "Toll Free" },
	{ "856", "South Western New Jersey" },
	{ "857", "Massachusetts" },
	{ "858", "Southern California" },
	{ "859", "Northern or Central Kentucky" },
	{ "860", "Connecticut" },
	{ "862", "Northern New Jersey" },
	{ "863", "Florida" },
	{ "864", "South Carolina" },
	{ "865", "Eastern Tennessee" },
	{ "866", "Toll Free" },
	{ "867", "Canada" },
	{ "868", "Trinidad or Tobago" },
	{ "869", "Saint Kitts or Nevis" },
	{ "870", "Arkansas" },
	{ "872", "Illinois" },
	{ "876", "Jamaica" },
	{ "877", "Toll Free" },
	{ "878", "Pittsburgh" },
	{ "880", "Toll Free" },
	{ "881", "Toll Free" },
	{ "882", "Toll Free" },
	{ "888", "Toll Free" },
	{ "898", "Voice over I.P. service" },
	{ "900", "Toll" },
	{ "901", "Western Tennessee" },
	{ "902", "Canada" },
	{ "903", "North Eastern Texas" },
	{ "904", "Northern Florida" },
	{ "905", "Canada" },
	{ "906", "Upper Peninsula Michigan" },
	{ "907", "Alaska" },
	{ "908", "Central New Jersey" },
	{ "909", "California" },
	{ "910", "Southern Central North Carolina" },
	{ "911", "Emergency" },
	{ "912", "South Eastern Georgia" },
	{ "913", "Kansas" },
	{ "914", "Southern New York" },
	{ "915", "Western Texas" },
	{ "916", "North Eastern California" },
	{ "917", "New York" },
	{ "918", "Eastern Oklahoma" },
	{ "919", "Eastern North Carolina" },
	{ "920", "North Eastern Wisconsin" },
	{ "925", "California" },
	{ "927", "Florida" },
	{ "928", "Central or Northern Arizona" },
	{ "931", "Middle Tennessee" },
	{ "935", "Southern California" },
	{ "936", "South Eastern Texas" },
	{ "937", "South Western Ohio" },
	{ "939", "Puerto Rico" },
	{ "940", "Northern Central Texas" },
	{ "941", "South Western Florida" },
	{ "947", "Michigan" },
	{ "949", "California" },
	{ "951", "California" },
	{ "952", "Minnesota" },
	{ "954", "Florida" },
	{ "956", "Texas" },
	{ "957", "New Mexico" },
	{ "959", "Connecticut" },
	{ "970", "Northern or Western Colorado" },
	{ "971", "Oregon" },
	{ "972", "Texas" },
	{ "973", "Northern New Jersey" },
	{ "975", "Northern Missouri" },
	{ "976", "Unknown" },
	{ "978", "Massachusetts" },
	{ "979", "South Eastern Texas" },
	{ "980", "North Carolina" },
	{ "984", "Eastern North Carolina" },
	{ "985", "Eastern Louisiana" },
	{ "989", "Upper Central Michigan" },
	{ "999", "Unavailable" }
    };

    private Map<String,String> area_code_map;

    public GeoLocator() {
	area_code_map = new HashMap<String,String>();

	for(int i=0; i<area_codes.length; i++)
	    area_code_map.put(area_codes[i][0], area_codes[i][1]);
    }

    public String lookup(String area_code) {
	return area_code_map.get(area_code);
    }

    public String locate(String address) {
	String rv;
	int len = address.length();

	if(len == 12 && address.startsWith("+1"))
	    rv = lookup(address.substring(2, 5));
	else if(len == 11 && address.startsWith("1"))
	    rv = lookup(address.substring(1, 4));
	else if(len == 10)
	    rv = lookup(address.substring(0, 3));
	else
	    rv = null;
	
	return rv;
    }
}