/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.quuux.crier;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int preferences_title=0x7f040001;
        public static final int summary_phone_enabled=0x7f040003;
        public static final int summary_text_enabled=0x7f040005;
        public static final int summary_time_enabled=0x7f040007;
        public static final int title_phone_enabled=0x7f040002;
        public static final int title_text_enabled=0x7f040004;
        public static final int title_time_enabled=0x7f040006;
    }
    public static final class xml {
        public static final int preferences=0x7f030000;
    }
}
